# This file was automatically generated on Fri 29 May 2026 11:15:09 BST from
# source: /dls_sw/prod/R3.14.12.7/support/IDLAB-BUILDER/1-67/etc/makeIocs/TS02K-MO-IOC-01.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
TOP = .
include $(TOP)/configure/CONFIG

DIRS += configure
DIRS += TS02K-MO-IOC-01App/Db
DIRS += TS02K-MO-IOC-01App/src
DIRS += iocBoot/iocTS02K-MO-IOC-01
DIRS += TS02K-MO-IOC-01App/opi/edl

include $(TOP)/configure/RULES_TOP

