#!/bin/sh
# This file was automatically generated on Mon 20 Jul 2026 10:45:07 BST from
# source: /dls_sw/prod/R3.14.12.7/support/IDLAB-BUILDER/1-73/etc/makeIocs/TS02K-MO-IOC-01.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi


exec ./TS02K-MO-IOC-01 stTS02K-MO-IOC-01.boot
